import { DUMMY_USERS } from "./dummy-users";
import { DUMMY_PROJECTS } from "./dummy-projects";

export const DUMMY_TASKS = [
  {
    id : 't1',
    title: 'task1',
    users: [DUMMY_USERS[0],DUMMY_USERS[2],DUMMY_USERS[3]],
    project: DUMMY_PROJECTS[0] ,
    completed : true,
    deadline : '2025-09-01',
    status : 'CM' ,
    start_date : '2025-04-09',
    completed_date : '' ,
  },
  {
    id : 't2',
    title: 'task2',
    users: [DUMMY_USERS[0]],
    project: DUMMY_PROJECTS[0] ,
    completed : false,
    deadline : '2025-09-04',
    status : 'NS' ,
    start_date : '2025-04-09',
    completed_date : '' ,
  },
  {
    id : 't3',
    title: 'task3',
    users: [DUMMY_USERS[4],DUMMY_USERS[2]],
    project: DUMMY_PROJECTS[1] ,
    completed : false,
    deadline : '2025-09-08',
    status : 'NS' ,
    start_date : '2025-04-09',
    completed_date : '' ,
  },
  {
    id : 't4',
    title: 'task4',
    users: [DUMMY_USERS[0],DUMMY_USERS[2],DUMMY_USERS[5]],
    project: DUMMY_PROJECTS[2] ,
    completed : false,
    deadline : '2025-10-01',
    status : 'IP' ,
    start_date : '2025-04-09',
    completed_date : '' ,
  },
  {
    id : 't5',
    title: 'task5',
    users: [],
    project: DUMMY_PROJECTS[0] ,
    completed : false,
    deadline : '2025-12-01',
    status : 'NS' ,
    start_date : '2025-04-09',
    completed_date : '' ,
  },
];