export const DUMMY_TASKS = [
  {
    id : 't1',
    user_id: 'u1',
    title: 'task1',
    completed : true,
    deadline : '2025-09-01',
  },
  {
    id : 't2',
    user_id: 'u2',
    title: 'task2',
    completed : false,
    deadline : '2025-09-01',
  },
  {
    id : 't3',
    user_id: 'u1',
    title: 'task3',
    completed : false,
    deadline : '2025-09-01',
  },
  {
    id : 't4',
    user_id: 'u3',
    title: 'task4',
    completed : false,
    deadline : '2025-09-01',
  },
  {
    id : 't5',
    user_id: 'u2',
    title: 'task5',
    completed : false,
    deadline : '2025-09-01',
  },
  {
    id : 't6',
    user_id: 'u4',
    title: 'task6',
    completed : false,
    deadline : '2025-09-01',
  },
  {
    id : 't7',
    user_id: 'u3',
    title: 'task7',
    completed : false,
    deadline : '2025-09-01',
  },
];